CREATE DATABASE IF NOT EXISTS `DS1_LIB`;
USE `DS1_LIB`;
CREATE TABLE IF NOT EXISTS `Usuario`(
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(250) NOT NULL UNIQUE,
    `password` VARCHAR(500) NOT NULL
);
CREATE TABLE IF NOT EXISTS `Livros`(
    `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `titulo` VARCHAR(250) NOT NULL,
    `ano` INTEGER NOT NULL,
    `editora` VARCHAR(250) NOT NULL,
    `autores` VARCHAR(500) NOT NULL,
    `qt` INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS `LivrosEmprestados`(
    `usuario` INTEGER NOT NULL,
    `livro` INTEGER NOT NULL,
    `dataSaida` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `dataEntrega` DATETIME NOT NULL,
    FOREIGN KEY(usuario) REFERENCES `Usuario`(id),
    FOREIGN KEY(livro) REFERENCES `Livros`(id)
);


